### PR TITLE
remove table clear

### LINKED ISSUE #22: Crashes if there is a shape in setup()
This does not work
```
function setup() {
	createCanvas(200,200);
	ellipse(20,20,20,20);
	
}
function draw() {
	
}
```

But, this does 
```
function setup() {
	createCanvas(200,200);
}
function draw() {
	ellipse(20,20,20,20);
}
```

### PR DESCRIPTION
**Pull request by MathuraMG**
fixes #22

### CODE REVIEW

File: dist/p5-accessibility.js [hunk 1]
```diff
@@ -721,9 +721,7 @@ var color_lookup =
     "b" : 1,
     "name" : "magenta"
   },
-];
-
-function getElementById(id) {
+];;function getElementById(id) {
```
Comment (lm-n) [inline dist/p5-accessibility.js]: extra ';'

Comment (lm-n) [inline dist/p5-accessibility.js]: where is this double ';;' coming from?

**Comment by lm-n** [comment]
@MathuraMG It looks great! I tried it on the editor it doesn't give the error. I'm just wondering where that extra ';' comes from.

File: dist/p5-accessibility.js (hunk 1 above)
Comment (MathuraMG) [reply dist/p5-accessibility.js]: oh! Just looked at it, the gruntfile adds a ; between 2 files as a separator. Also, the _data.js file has a ; ending it since it's basically a giant object. Thus the 2 semicolons.
Maybe we should keep the gruntfile separator and remove the one in _data.js?

Comment (lm-n) [reply dist/p5-accessibility.js]: yes! sounds good

**Comment by MathuraMG** [comment]
@lm-n done!
